description: clean data

target:
  service: sing
  name: msrresrchvc

environment:
  # image: amlt-sing/datacopy-adls # disappeared
  # image: python:3.9-buster # seems amlt doesn't support it
  image: amlt-sing/pytorch-1.8.0-cuda11.1-cudnn8-devel
  setup:
    - python -m pip install --upgrade pip --user
    - pip install wget --user
    - pip install numpy --user
    - pip install regex --user
    - pip install tqdm --user
    - pip install langdetect --user
    - pip install nltk --user
    - pip install ftfy --user
    - pip install fasttext --user
    - pip install spacy --user
    - df -h
code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR/

storage:
  # storage account and container where the ImageNet tar balls are contained
  output:
    storage_account_name: vlpretraineastus
    container_name: crawl-text
    mount_dir: /output

jobs:
 - name: $JOB_NAME
   sku: 8C64
   priority: High
   execution_mode: basic
   azml_int: True
   command: 
   - python -m spacy download en
   - cd /tmp/code; git clone https://github.com/weiyx16/deduplicate-text-datasets
   - cd /tmp/code/deduplicate-text-datasets; bash cleanPileCC.sh
   submit_args:
      env:
       {
         SHARED_MEMORY_PERCENT: 1.0,
       }